schema_version = 3

[project]
uuid = "bbc82ff2-14b4-4454-9445-3a299ae9e62f"
name = "numeralform-gold"

[ledgers.taskledger.mounts.data]
storage = "external"
root = "../ledger"

[ledgers.taskledger.mounts.runtime]
storage = "user-data"

[ledgers.taskledger.mounts.logs]
storage = "user-data"

[ledgers.taskledger.mounts.indexes]
storage = "cache"
